//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE_DETAIL
    {
        public int RecipeID { get; set; }
        public int IngredientID { get; set; }
        public double Quantity { get; set; }
        public Nullable<int> UnitID { get; set; }
    
        public virtual INGREDIENT INGREDIENT { get; set; }
        public virtual RECIPE RECIPE { get; set; }
        public virtual UNIT UNIT { get; set; }
    }
}
