//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROCERY
    {
        public int ID { get; set; }
        public int AccountID { get; set; }
        public int RecipeID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual RECIPE RECIPE { get; set; }
    }
}
