//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECIPE()
        {
            this.COMMENT = new HashSet<COMMENT>();
            this.RECIPE_DETAIL = new HashSet<RECIPE_DETAIL>();
            this.STEPTODO = new HashSet<STEPTODO>();
            this.TAG = new HashSet<TAG>();
            this.COOKSNAP = new HashSet<COOKSNAP>();
            this.FAVORITE = new HashSet<FAVORITE>();
            this.GROCERY = new HashSet<GROCERY>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Describe { get; set; }
        public string MainImage { get; set; }
        public Nullable<int> CookTime { get; set; }
        public Nullable<int> PrepTime { get; set; }
        public Nullable<int> Servings { get; set; }
        public string Difficulty { get; set; }
        public Nullable<int> Status { get; set; }
        public string RejectReason { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECIPE_DETAIL> RECIPE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STEPTODO> STEPTODO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAG> TAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COOKSNAP> COOKSNAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVORITE> FAVORITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROCERY> GROCERY { get; set; }
    }
}
