//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingShare.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CookingShareDBEntities : DbContext
    {
        public CookingShareDBEntities()
            : base("name=CookingShareDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNT { get; set; }
        public virtual DbSet<BANNER> BANNER { get; set; }
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<COMMENT> COMMENT { get; set; }
        public virtual DbSet<INGREDIENT> INGREDIENT { get; set; }
        public virtual DbSet<PROFILE> PROFILE { get; set; }
        public virtual DbSet<RECIPE> RECIPE { get; set; }
        public virtual DbSet<RECIPE_DETAIL> RECIPE_DETAIL { get; set; }
        public virtual DbSet<STEPTODO> STEPTODO { get; set; }
        public virtual DbSet<SYSTEM_SETTING> SYSTEM_SETTING { get; set; }
        public virtual DbSet<TAG> TAG { get; set; }
        public virtual DbSet<TIP> TIP { get; set; }
        public virtual DbSet<UNIT> UNIT { get; set; }
        public virtual DbSet<COOKSNAP> COOKSNAP { get; set; }
        public virtual DbSet<COOKSNAP_COMMENT> COOKSNAP_COMMENT { get; set; }
        public virtual DbSet<FAVORITE> FAVORITE { get; set; }
        public virtual DbSet<FOLLOW> FOLLOW { get; set; }
        public virtual DbSet<GROCERY> GROCERY { get; set; }
        public virtual DbSet<REPORT> REPORT { get; set; }
        public virtual DbSet<NOTIFICATION> NOTIFICATION { get; set; }
    }
}
