//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFILE
    {
        public int AccountID { get; set; }
        public string FullName { get; set; }
        public string Avatar { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Lifestyle { get; set; }
        public Nullable<double> CaloDaily { get; set; }
        public string Bio { get; set; }
        public string JobTitle { get; set; }
        public string Education { get; set; }
        public string CookingPhilosophy { get; set; }
        public string KitchenImage { get; set; }
        public string SocialLink { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
    }
}
